# config.yaml
database:
 host: localhost
 database: FDE
 user: postgres
 password: 12345678
 port: 5432


s3:
 bucket_name: dataen1
 region: us-east-1
 files:
   JSON/products.json: lnd_products_json
   JSON/sales.json: lnd_sales_json
   CSV/customers.csv: lnd_customers_csv
   CSV/products.csv: lnd_products_csv
   CSV/sales.csv: lnd_sales_csv


api:
 endpoints:
   https://dummyjson.com/products: lnd_products_api
   https://dummyjson.com/users: lnd_users_api
